export const multiLang = {
    en: {
      headerText: "Rail",
      PNR_Question: "Great to meet you. Kindly provide PNR number to proceed",
      submitButton: "submit",
      introQuestion: "PNR verified successfully. What brings you here today?",
      introQuestionBox: "What brings you here today?",
      selectionRequired: "Please select an option below:",
      categoriesArray: [
        "Passenger Services",
        "Ticketing and Reservation",
        "Security and Safety",
        "General Information",
      ],
      queryIntroMessage: "Please enter your query...",
      placeholderText: "Enter your message...",
      botThinkingText: "Thinking...",
      youHaveSelected: "You have selected",
      selectedContinuation: ". How can I assist you with this?",
    },
  
    hi: {
      headerText: "रेल",
      PNR_Question:
        "बड़ा अच्छा लगा आपसे मिल के। कृपया आगे बढ़ने के लिए पीएनआर नंबर प्रदान करें",
      submitButton: "प्रस्तुत",
      introQuestion:
        "पीएनआर सफलतापूर्वक सत्यापित हो गया है। आज आपको यहाँ क्यों लाया है?",
      introQuestionBox: "आज आपको यहाँ क्यों लाया है?",
      selectionRequired: "कृपया नीचे दिए गए विकल्प में से चुनें:",
      categoriesArray: [
        "यात्री सेवाएं",
        "टिकट और आरक्षण",
        "सुरक्षा और सुरक्षा",
        "सामान्य जानकारी",
      ],
      queryIntroMessage: "कृपया अपना प्रश्न दर्ज करें...",
      placeholderText: "अपना संदेश दर्ज करें...",
      botThinkingText: "सोच रहा है...",
      youHaveSelected: "आपने चयन किया है",
      selectedContinuation: "। मैं इसमें आपकी कैसे सहायता कर सकता हूँ?",
    },
    tm: {
      headerText: "ரயில்",
      PNR_Question:
        "உங்களை சந்தித்ததற்கு மிக்க மகிழ்ச்சி. தயவுசெய்து பிஎன்ஆர் எண்ணை வழங்கவும்",
      submitButton: "சமர்ப்பிக்கவும்",
      introQuestion:
        "பிஎன்ஆர் வெற்றிகரமாக சரிபார்க்கப்பட்டுள்ளது. உங்களை இன்று இங்கே என்ன கொண்டு வ இருக்கிறீர்கள்?",
      introQuestionBox: "இன்று உங்களை இங்கே என்ன கொண்டு வ இருக்கிறீர்கள்?",
      selectionRequired: "தயவுசெய்து கீழே உள்ள ஒன்றை தேர்ந்தெடுக்கவும்:",
      categoriesArray: [
        "பயணிகள் சேவைகள்",
        "டிக்கெட் மற்றும் ஆரக்கச்சன்",
        "பாதுகாப்பு மற்றும் பாதுகாப்பு",
        "பொது தகவல்",
      ],
      queryIntroMessage: "உங்கள் கேள்வியை உள்ளிடவும்",
      placeholderText: "உங்கள் செய்தியை உள்ளிடவும்...",
      botThinkingText: "சிந்திக்கிறது...",
      youHaveSelected: "நீங்கள் தேர்ந்தெடுத்துள்ளீர்கள்",
      selectedContinuation: ". இதுவரை நான் உங்களுக்கு எப்படி உதவ முடியும்?",
    },
  };
  
  export const availableDepartments = {
    //English
    "Passenger Services": [
      "Medical Assistance",
      "Facilities For women With special needs",
      "Divyangjan Facilities",
      "Passenger Amenities",
      "Cleanliness",
      "Water Availability",
      "Catering and Vending Service",
      "Miscellaneous",
      "Staff Behaviour",
      "Electrical Equipment",
      "Reserved Tickets",
      "Unreserved Tickets",
      "Refund of Tickets",
      "Overcrowding in Coaches",
      "Sexual Harassment/Misbehaviour",
      "Chain Pulling",
      "Nuisance by Unauthorized Persons",
      "Harassment/Extortion by Authorities",
      "Suspicious or Unclaimed Items",
      "Missing or Unresponsive Passenger",
      "Substance Abuse",
      "Violence/Disorder",
      "Passenger Accident",
      "Other Issues",
      "Luggage/Parcels",
      "Goods",
    ],
    "Ticketing and Reservation": [
      "Reserved Tickets",
      "Unreserved Tickets",
      "Refund of Tickets",
      "Overcrowding in Coaches",
      "Medical Assistance",
      "Facilities For women With special needs",
      "Divyangjan Facilities",
      "Passenger Amenities",
      "Cleanliness",
      "Water Availability",
      "Catering and Vending Service",
      "Miscellaneous",
      "Staff Behaviour",
      "Electrical Equipment",
      "Sexual Harassment/Misbehaviour",
      "Chain Pulling",
      "Nuisance by Unauthorized Persons",
      "Harassment/Extortion by Authorities",
      "Suspicious or Unclaimed Items",
      "Missing or Unresponsive Passenger",
      "Substance Abuse",
      "Violence/Disorder",
      "Passenger Accident",
      "Other Issues",
      "Luggage/Parcels",
      "Goods",
    ],
    "Security and Safety": [
      "Sexual Harassment/Misbehaviour",
      "Chain Pulling",
      "Nuisance by Unauthorized Persons",
      "Harassment/Extortion by Authorities",
      "Suspicious or Unclaimed Items",
      "Missing or Unresponsive Passenger",
      "Substance Abuse",
      "Violence/Disorder",
      "Passenger Accident",
      "Other Issues",
      "Medical Assistance",
      "Facilities For women With special needs",
      "Divyangjan Facilities",
      "Passenger Amenities",
      "Cleanliness",
      "Water Availability",
      "Catering and Vending Service",
      "Miscellaneous",
      "Staff Behaviour",
      "Electrical Equipment",
      "Reserved Tickets",
      "Unreserved Tickets",
      "Refund of Tickets",
      "Overcrowding in Coaches",
      "Luggage/Parcels",
      "Goods",
    ],
    "General Information": [
      "Luggage/Parcels",
      "Goods",
      "Medical Assistance",
      "Facilities For women With special needs",
      "Divyangjan Facilities",
      "Passenger Amenities",
      "Cleanliness",
      "Water Availability",
      "Catering and Vending Service",
      "Miscellaneous",
      "Staff Behaviour",
      "Electrical Equipment",
      "Reserved Tickets",
      "Unreserved Tickets",
      "Refund of Tickets",
      "Overcrowding in Coaches",
      "Sexual Harassment/Misbehaviour",
      "Chain Pulling",
      "Nuisance by Unauthorized Persons",
      "Harassment/Extortion by Authorities",
      "Suspicious or Unclaimed Items",
      "Missing or Unresponsive Passenger",
      "Substance Abuse",
      "Violence/Disorder",
      "Passenger Accident",
      "Other Issues",
    ],
  
    //Hindi
    "यात्री सेवाएं": [
      "Medical Assistance",
      "Facilities For women With special needs",
      "Divyangjan Facilities",
      "Passenger Amenities",
      "Cleanliness",
      "Water Availability",
      "Catering and Vending Service",
      "Miscellaneous",
      "Staff Behaviour",
      "Electrical Equipment",
      "Reserved Tickets",
      "Unreserved Tickets",
      "Refund of Tickets",
      "Overcrowding in Coaches",
      "Sexual Harassment/Misbehaviour",
      "Chain Pulling",
      "Nuisance by Unauthorized Persons",
      "Harassment/Extortion by Authorities",
      "Suspicious or Unclaimed Items",
      "Missing or Unresponsive Passenger",
      "Substance Abuse",
      "Violence/Disorder",
      "Passenger Accident",
      "Other Issues",
      "Luggage/Parcels",
      "Goods",
    ],
    "टिकट और आरक्षण": [
      "Medical Assistance",
      "Facilities For women With special needs",
      "Divyangjan Facilities",
      "Passenger Amenities",
      "Cleanliness",
      "Water Availability",
      "Catering and Vending Service",
      "Miscellaneous",
      "Staff Behaviour",
      "Electrical Equipment",
      "Reserved Tickets",
      "Unreserved Tickets",
      "Refund of Tickets",
      "Overcrowding in Coaches",
      "Sexual Harassment/Misbehaviour",
      "Chain Pulling",
      "Nuisance by Unauthorized Persons",
      "Harassment/Extortion by Authorities",
      "Suspicious or Unclaimed Items",
      "Missing or Unresponsive Passenger",
      "Substance Abuse",
      "Violence/Disorder",
      "Passenger Accident",
      "Other Issues",
      "Luggage/Parcels",
      "Goods",
    ],
    "सुरक्षा और सुरक्षा": [
      "Medical Assistance",
      "Facilities For women With special needs",
      "Divyangjan Facilities",
      "Passenger Amenities",
      "Cleanliness",
      "Water Availability",
      "Catering and Vending Service",
      "Miscellaneous",
      "Staff Behaviour",
      "Electrical Equipment",
      "Reserved Tickets",
      "Unreserved Tickets",
      "Refund of Tickets",
      "Overcrowding in Coaches",
      "Sexual Harassment/Misbehaviour",
      "Chain Pulling",
      "Nuisance by Unauthorized Persons",
      "Harassment/Extortion by Authorities",
      "Suspicious or Unclaimed Items",
      "Missing or Unresponsive Passenger",
      "Substance Abuse",
      "Violence/Disorder",
      "Passenger Accident",
      "Other Issues",
      "Luggage/Parcels",
      "Goods",
    ],
    "जनरल जानकारी": [
      "Medical Assistance",
      "Facilities For women With special needs",
      "Divyangjan Facilities",
      "Passenger Amenities",
      "Cleanliness",
      "Water Availability",
      "Catering and Vending Service",
      "Miscellaneous",
      "Staff Behaviour",
      "Electrical Equipment",
      "Reserved Tickets",
      "Unreserved Tickets",
      "Refund of Tickets",
      "Overcrowding in Coaches",
      "Sexual Harassment/Misbehaviour",
      "Chain Pulling",
      "Nuisance by Unauthorized Persons",
      "Harassment/Extortion by Authorities",
      "Suspicious or Unclaimed Items",
      "Missing or Unresponsive Passenger",
      "Substance Abuse",
      "Violence/Disorder",
      "Passenger Accident",
      "Other Issues",
      "Luggage/Parcels",
      "Goods",
    ],
  
    //Tamil
    "பயணிகள் சேவைகள்": [
      "Medical Assistance",
      "Facilities For women With special needs",
      "Divyangjan Facilities",
      "Passenger Amenities",
      "Cleanliness",
      "Water Availability",
      "Catering and Vending Service",
      "Miscellaneous",
      "Staff Behaviour",
      "Electrical Equipment",
      "Reserved Tickets",
      "Unreserved Tickets",
      "Refund of Tickets",
      "Overcrowding in Coaches",
      "Sexual Harassment/Misbehaviour",
      "Chain Pulling",
      "Nuisance by Unauthorized Persons",
      "Harassment/Extortion by Authorities",
      "Suspicious or Unclaimed Items",
      "Missing or Unresponsive Passenger",
      "Substance Abuse",
      "Violence/Disorder",
      "Passenger Accident",
      "Other Issues",
      "Luggage/Parcels",
      "Goods",
    ],
    "டிக்கெட் மற்றும் ஆரக்கச்சன்": [
      "Medical Assistance",
      "Facilities For women With special needs",
      "Divyangjan Facilities",
      "Passenger Amenities",
      "Cleanliness",
      "Water Availability",
      "Catering and Vending Service",
      "Miscellaneous",
      "Staff Behaviour",
      "Electrical Equipment",
      "Reserved Tickets",
      "Unreserved Tickets",
      "Refund of Tickets",
      "Overcrowding in Coaches",
      "Sexual Harassment/Misbehaviour",
      "Chain Pulling",
      "Nuisance by Unauthorized Persons",
      "Harassment/Extortion by Authorities",
      "Suspicious or Unclaimed Items",
      "Missing or Unresponsive Passenger",
      "Substance Abuse",
      "Violence/Disorder",
      "Passenger Accident",
      "Other Issues",
      "Luggage/Parcels",
      "Goods",
    ],
    "பாதுகாப்பு மற்றும் பாதுகாப்பு": [
      "Medical Assistance",
      "Facilities For women With special needs",
      "Divyangjan Facilities",
      "Passenger Amenities",
      "Cleanliness",
      "Water Availability",
      "Catering and Vending Service",
      "Miscellaneous",
      "Staff Behaviour",
      "Electrical Equipment",
      "Reserved Tickets",
      "Unreserved Tickets",
      "Refund of Tickets",
      "Overcrowding in Coaches",
      "Sexual Harassment/Misbehaviour",
      "Chain Pulling",
      "Nuisance by Unauthorized Persons",
      "Harassment/Extortion by Authorities",
      "Suspicious or Unclaimed Items",
      "Missing or Unresponsive Passenger",
      "Substance Abuse",
      "Violence/Disorder",
      "Passenger Accident",
      "Other Issues",
      "Luggage/Parcels",
      "Goods",
    ],
    "பொது தகவல்": [
      "Medical Assistance",
      "Facilities For women With special needs",
      "Divyangjan Facilities",
      "Passenger Amenities",
      "Cleanliness",
      "Water Availability",
      "Catering and Vending Service",
      "Miscellaneous",
      "Staff Behaviour",
      "Electrical Equipment",
      "Reserved Tickets",
      "Unreserved Tickets",
      "Refund of Tickets",
      "Overcrowding in Coaches",
      "Sexual Harassment/Misbehaviour",
      "Chain Pulling",
      "Nuisance by Unauthorized Persons",
      "Harassment/Extortion by Authorities",
      "Suspicious or Unclaimed Items",
      "Missing or Unresponsive Passenger",
      "Substance Abuse",
      "Violence/Disorder",
      "Passenger Accident",
      "Other Issues",
      "Luggage/Parcels",
      "Goods",
    ],
  };
  